# This workflow will test instructions from https://github.com/jfrog/setup-jfrog-cli?tab=readme-ov-file#storing-the-connection-details-using-separate-environment-variables

name: JFrog CLI Test

on:
    workflow_dispatch:
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: jfrog/setup-jfrog-cli@v3
      env:
        # JFrog platform url (for example: https://acme.jfrog.io) 
        JF_URL: ${{ vars.JF_URL }}
        # JFrog Platform access token
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
    - run: |
        echo "$JF_URL"
        jf rt ping